<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWvw5xkx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWvw5xkx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWvw5xkx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWvw5xkx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWvw5xkx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Wvw5xkx',
    'container.build_id' => 'd538ca34',
    'container.build_time' => 1645051615,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWvw5xkx');
