<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'evenement' => [[], ['_controller' => 'App\\Controller\\EvenementController::index'], [], [['text', '/evenement']], [], []],
    'EvSalle' => [[], ['_controller' => 'App\\Controller\\EvenementController::EvSalle'], [], [['text', '/EvSalle']], [], []],
    'afficheE' => [[], ['_controller' => 'App\\Controller\\EvenementController::afficheEvenement'], [], [['text', '/afficheE']], [], []],
    'ajoutE' => [[], ['_controller' => 'App\\Controller\\EvenementController::ajoutE'], [], [['text', '/ajoutE/']], [], []],
    'suppE' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::supp'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/supp']], [], []],
    'modifE' => [['id'], ['_controller' => 'App\\Controller\\EvenementController::modifE'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifE']], [], []],
    'reservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::index'], [], [['text', '/reservation']], [], []],
    'ajoutR' => [[], ['_controller' => 'App\\Controller\\ReservationController::resnew'], [], [['text', '/ajoutR/']], [], []],
    'afficheRadmin' => [[], ['_controller' => 'App\\Controller\\ReservationController::afficheEvenement'], [], [['text', '/afficheRadmin']], [], []],
    'ajoutResAdmin' => [[], ['_controller' => 'App\\Controller\\ReservationController::res'], [], [['text', '/ajoutResAdmin/']], [], []],
    'suppRes' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::suppres'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/suppRes']], [], []],
    'modifRes' => [['id'], ['_controller' => 'App\\Controller\\ReservationController::modifier'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/modifRes']], [], []],
    'ResSearch' => [[], ['_controller' => 'App\\Controller\\ReservationController::liseress'], [], [['text', '/ResSearch']], [], []],
];
